CFLAGS += -fPIC
OBJ = ast.o lexer.o lib.o parser.o strutils.o tree.o

cascad: main.o $(OBJ)
	$(CC) $(LDFLAGS) -o $@ $^

libcascad.so: $(OBJ)
	$(CC) $(LDFLAGS) -shared -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<

y.tab.h: parser.y
	yacc -d parser.y

ast.o: ast.h
ast.h: tree.h
lexer.o: ast.h lexer.h y.tab.h
lib.o: lexer.h parser.h
main.o: lib.h
parser.o: ast.h lexer.h strutils.h
parser.h: ast.h
strutils.o: strutils.h
tree.o: tree.h

clean:
	$(RM) *.o y.tab.* cascad*

distclean:
	$(RM) *.o y.tab.* cascad* config.*

.PHONY: clean distclean
